// Share links made before issue #144 carried the payload in the query string:
// ?z= (deflated JSON), ?state= (plain JSON) and ?e= (password-encrypted). The
// fixtures were generated by that code (fixtures/share-legacy.json); every one
// of them must keep opening, forever — they are in chats, slides and papers.
'use strict';
const fs = require('fs');
const path = require('path');
const H = require('../harness');

const FIX = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'fixtures', 'share-legacy.json'), 'utf8'));
const BASE = (process.env.CRYSVIZ_URL || 'http://localhost:8123/index.html').split(/[?#]/)[0];

const RESTORED = async () => {
  const { general } = await import('./state/store.js');
  const { getActiveStructure } = await import('./state/structures.js');
  const s = getActiveStructure();
  const c = s?.atoms?.[0]?.color;
  return {
    loaded: general.sharedStructureLoaded === true,
    atoms: s?.atoms?.length ?? 0,
    atom0: typeof c === 'number' ? '#' + c.toString(16).padStart(6, '0') : String(c).toLowerCase(),
    atomSize: general.atomSize,
    search: location.search,
  };
};

(async () => {
  const { browser, page, errors } = await H.launchApp({ navigate: false });

  for (const kind of ['z', 'state', 'e']) {
    await page.goto('about:blank');
    await page.goto(BASE + FIX.links[kind], { waitUntil: 'load', timeout: 90000 });
    if (kind === 'e') {
      // Wrong password first: the prompt must come back with the retry note.
      const prompt = async (pw) => {
        await page.waitForSelector('#sharePasswordModal:not([hidden])', { timeout: 40000 });
        await page.fill('#sharePwInput', pw);
        await page.click('#sharePwOpen');
      };
      await prompt('wrong-password');
      await page.waitForSelector('#sharePasswordModal:not([hidden]) #sharePwError:not([hidden])', { timeout: 40000 });
      H.check('?e=: a wrong password asks again', true);
      await prompt(FIX.password);
    }
    const r = await H.waitFor(page, async () => {
      const { general } = await import('./state/store.js');
      return general.sharedStructureLoaded === true;
    }, { timeout: 60000, interval: 1000 }) && await page.evaluate(RESTORED);
    H.check(`legacy ?${kind}= link restores structure and styling`,
      r && r.atoms === FIX.expected.atoms && r.atom0 === FIX.expected.atom0Color
        && Math.abs(r.atomSize - FIX.expected.atomSize) < 1e-9,
      JSON.stringify(r));
    H.check(`legacy ?${kind}= payload is stripped from the address bar`, r && !/[?&](z|state|e)=/.test(r.search), r?.search);
  }

  H.check('no page errors', errors.length === 0, errors.join(' | '));
  await H.finish(browser);
})().catch(H.crash);
