// Unit tests for the Gaussian cube parser (docs/io/cubeParse.js).
// Run: make unittest   (or: node --test tools/unittest/)
//
// The same water-in-a-box file is written once in Bohr (positive grid counts)
// and once in Angstrom (negative grid counts); both must parse to the same
// Angstrom geometry and the same grid.
import test from 'node:test';
import assert from 'node:assert/strict';

import { parseCube, BOHR_TO_ANGSTROM as B } from '../../docs/io/cubeParse.js';

const GRID = [2, 3, 4];
const STEP_BOHR = 0.5;
const ORIGIN_BOHR = [-1, -2, -3];
const WATER_BOHR = [
  [8, 0, 0, 0.2],
  [1, 0, 1.4, -0.9],
  [1, 0, -1.4, -0.9],
];
// Value at grid point (x, y, z) for dataset d: unique, so ordering is checked.
const value = (x, y, z, d = 0) => 100 * x + 10 * y + z + 1000 * d;

const fmt = (v) => v.toFixed(6);

/** Data section in file order: x slowest, z fastest, `nval` values per point,
 *  six to a line with a break after every z row, as Gaussian writes it. */
function dataLines(nval = 1) {
  const out = [];
  for (let x = 0; x < GRID[0]; x++) {
    for (let y = 0; y < GRID[1]; y++) {
      const row = [];
      for (let z = 0; z < GRID[2]; z++) {
        for (let d = 0; d < nval; d++) row.push(value(x, y, z, d).toExponential(5));
      }
      for (let i = 0; i < row.length; i += 6) out.push(' ' + row.slice(i, i + 6).join(' '));
    }
  }
  return out;
}

/** The water cube in `units`: coordinates converted and grid counts signed. */
function waterCube(units, { natoms = 3, extra = [], nval = 1, comment = 'Water density' } = {}) {
  const k = units === 'angstrom' ? B : 1;
  const sign = units === 'angstrom' ? -1 : 1;
  return [
    comment,
    'Generated by the cubeparse test',
    `${natoms} ${ORIGIN_BOHR.map((c) => fmt(c * k)).join(' ')}`,
    ...GRID.map((n, axis) => {
      const step = [0, 0, 0];
      step[axis] = STEP_BOHR * k;
      return `${sign * n} ${step.map(fmt).join(' ')}`;
    }),
    ...WATER_BOHR.map(([z, x, y, zc]) => `${z} ${fmt(z)} ${[x, y, zc].map((c) => fmt(c * k)).join(' ')}`),
    ...extra,
    ...dataLines(nval),
  ].join('\n');
}

const close = (a, b, tol = 1e-5) => Math.abs(a - b) <= tol;
function assertVecClose(actual, expected, label) {
  assert.equal(actual.length, expected.length, `${label}: length`);
  actual.forEach((v, i) => assert.ok(close(v, expected[i]), `${label}[${i}]: ${v} vs ${expected[i]}`));
}

function assertGeometry(cube) {
  assert.deepEqual(cube.grid, GRID);
  GRID.forEach((n, axis) => {
    const step = [0, 0, 0];
    step[axis] = STEP_BOHR * B;
    assertVecClose(cube.voxel[axis], step, `voxel ${axis}`);
    // The cell is n * step, and positive: a negative count only flags units.
    assertVecClose(cube.lattice[axis], step.map((c) => c * n), `lattice ${axis}`);
  });
  assertVecClose(cube.origin, ORIGIN_BOHR.map((c) => c * B), 'origin');
  assert.deepEqual(cube.atoms.map((a) => a.atomicNumber), [8, 1, 1]);
  cube.atoms.forEach((a, i) => assertVecClose(a.position, WATER_BOHR[i].slice(1).map((c) => c * B), `atom ${i}`));
}

function assertValues(values, d = 0) {
  const [nx, ny] = GRID;
  for (let x = 0; x < GRID[0]; x++) {
    for (let y = 0; y < GRID[1]; y++) {
      for (let z = 0; z < GRID[2]; z++) {
        assert.equal(values[x + nx * (y + ny * z)], value(x, y, z, d), `value at ${x},${y},${z} dataset ${d}`);
      }
    }
  }
}

test('Bohr header (positive grid counts) is converted to Angstrom', () => {
  const cube = parseCube(waterCube('bohr'));
  assert.equal(cube.units, 'bohr');
  assert.equal(cube.label, 'Water density Generated by the cubeparse test');
  assertGeometry(cube);
  assert.equal(cube.values.length, 1);
  assertValues(cube.values[0]);
});

test('Angstrom header (negative grid counts) parses to the same geometry', () => {
  const cube = parseCube(waterCube('angstrom'));
  assert.equal(cube.units, 'angstrom');
  assertGeometry(cube);
  assert.equal(cube.values.length, 1);
  assertValues(cube.values[0]);
});

test('Bohr and Angstrom versions of one file agree', () => {
  const bohr = parseCube(waterCube('bohr'));
  const ang = parseCube(waterCube('angstrom'));
  bohr.lattice.forEach((row, i) => assertVecClose(ang.lattice[i], row, `lattice ${i}`));
  bohr.atoms.forEach((a, i) => assertVecClose(ang.atoms[i].position, a.position, `atom ${i}`));
  assert.deepEqual(Array.from(ang.values[0]), Array.from(bohr.values[0]));
});

test('negative NATOMS: wrapped dataset-id record, one array per orbital', () => {
  // 12 ids is more than the ten Gaussian writes per line, so the record wraps.
  const ids = Array.from({ length: 12 }, (_, i) => i + 5);
  const extra = [` 12 ${ids.slice(0, 10).join(' ')}`, ` ${ids.slice(10).join(' ')}`];
  for (const units of ['bohr', 'angstrom']) {
    const cube = parseCube(waterCube(units, { natoms: -3, extra, nval: 12 }));
    assertGeometry(cube);
    assert.deepEqual(cube.datasetIds, ids);
    assert.equal(cube.values.length, 12);
    cube.values.forEach((v, d) => assertValues(v, d));
  }
});

test('a blank first comment line does not shift the header', () => {
  const cube = parseCube(waterCube('bohr', { comment: '' }));
  assertGeometry(cube);
  assertValues(cube.values[0]);
});

test('a truncated data section is an error, not a partly zero grid', () => {
  const text = waterCube('bohr').split('\n').slice(0, -2).join('\n');
  assert.throws(() => parseCube(text), /expected 24 data values/);
});
